// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYq_eWcQlbQSqFLPG7N-pPh3OuUhjP4s',
    appId: '1:158504325848:web:e5144fad07b3d329183dad',
    messagingSenderId: '158504325848',
    projectId: 'nomad-final-exam',
    authDomain: 'nomad-final-exam.firebaseapp.com',
    storageBucket: 'nomad-final-exam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3T3GC5up-KwOIGGlxyhCJl1yzeW1mldk',
    appId: '1:158504325848:android:484e6e2c51f0c9ce183dad',
    messagingSenderId: '158504325848',
    projectId: 'nomad-final-exam',
    storageBucket: 'nomad-final-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0OGdPvUNDxaw68Ly9HJMdfpX86Pm7oz4',
    appId: '1:158504325848:ios:d59a836bc2b4c57c183dad',
    messagingSenderId: '158504325848',
    projectId: 'nomad-final-exam',
    storageBucket: 'nomad-final-exam.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0OGdPvUNDxaw68Ly9HJMdfpX86Pm7oz4',
    appId: '1:158504325848:ios:a9843ed1c2097590183dad',
    messagingSenderId: '158504325848',
    projectId: 'nomad-final-exam',
    storageBucket: 'nomad-final-exam.appspot.com',
    iosBundleId: 'com.example.finalExam.RunnerTests',
  );
}
